### ISSUE TITLE
Home store routing example not working properly

### ISSUE THREAD

**Issue by Lauel09** [flet-dev/examples#100]
Hello!
I was running the `home-store.py` routing example from [here](https://github.com/flet-dev/examples/blob/main/python/apps/routing-navigation/home-store.py), and I faced this issue:
1. It starts with this:
![image](https://github.com/flet-dev/examples/assets/19989996/95602101-8224-4b1d-a923-935ec24542f7)
2. Then I click on 'Visit Store':
![image](https://github.com/flet-dev/examples/assets/19989996/f4bd8940-d358-4f07-97d1-f88de02d05a2)
3. I do the step 1 and 2 twice, then I land on this:
![image](https://github.com/flet-dev/examples/assets/19989996/5a66ac6c-2766-4e66-9140-827e4e3bf3f7)
This produces ping sound everytime, I click by mouse.
Terminal:-
```fish
(python_flutter) ➜  python_flutter python3 src/main.py

(flet:19284): Gdk-CRITICAL **: 13:47:24.916: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

```

My system:
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 6.2.0-36-generic

**Comment by ndonkoHenri** [comment]
You are right! this is a bug which popped up in v0.12.0 to be precise.

**Comment by Lauel09** [comment]
> You are right! this is a bug which popped up in v0.12.0 to be precise.
> 
> I am just from noticing that, the content of the window reappears when the window is moved.

Oh, yes when I was trying to screenshot it, it returned back to normal, then I did the same thing and it disappeared.

What is the bug? Can you give me brief, if it's possible, I might be able to contribute.

**Comment by FeodorFitsner** [comment]
It's a bug, looking into that.

**Comment by FeodorFitsner** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/2082
