### ISSUE TITLE
Chip control has no way of controlling text color when selected

### ISSUE THREAD

**Issue by Petapton** [flet-dev/examples#103]
Hello, I found out that `Chip` cannot use different label colors for selected and unselected states. Instead, the check mark color can be changed.

Here is an example:
```
# ...
[
    ft.Chip(
        label=ft.Text("Chip"),
        selected_color=ft.colors.PRIMARY,
        check_color=ft.colors.ON_PRIMARY,
        on_select=lambda _: page.update(),
    )
]
# ...
```
Result:
![chip-demo](https://github.com/flet-dev/examples/assets/14984292/c59eaa3a-a39d-49d4-915c-ef8c3f32820b)

It would be nice if there were a way to set also the label to `colors.PRIMARY` when selected.
I think an option could be a `selected_label_color`-ish argument. Alternatively, the `check_color` could be used on label when selected.

**Comment by ndonkoHenri** [comment]
> I found out that Chip cannot use different label colors for selected and unselected states.

Make the changes in your callback function:

```python
import flet as ft


def main(page: ft.Page):
    def chip_callback(e):
        x.label_style.color = ft.colors.YELLOW if x.selected else ft.colors.RED
        page.update()

    x = ft.Chip(
        label=ft.Text(
            "Chip",
            # color=ft.colors.AMBER
        ),
        label_style=ft.TextStyle(weight=ft.FontWeight.BOLD, italic=True, color=ft.colors.RED),
        selected_color=ft.colors.PRIMARY,
        check_color=ft.colors.ON_PRIMARY,
        on_select=chip_callback,
    )

    page.add(x)


ft.app(target=main)
```
