### ISSUE TITLE
Page object is not callable

### ISSUE THREAD

**Issue by Viraj-01** [flet-dev/examples#118]
session_handler(page) 
TypeError: 'Page' object is not callable

Connected to MySQL database successfully.
Unhandled error processing page session : Traceback 
(most recent call last):  
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet_runtime\app.py", line 357, in on_session_created
    session_handler(page) 
TypeError: 'Page' object is not callable

can't run the app due to this error

**Comment by FeodorFitsner** [comment]
Would you care to provide more details as issue template suggests?
