### ISSUE TITLE
Are there any 'checked' menuitem like this?

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/examples#131]
Are there any 'checked' menuitem like this?
![image](https://github.com/flet-dev/examples/assets/2862064/4f741459-f85e-4beb-a38d-9a0351110d93)

**Comment by ndonkoHenri** [comment]
Nope, there is no direct checkmark.
But, you can play with the existing props. Ex: set the `MenuItemButton.leading` prop to an `Icon` (checkmark), and switch/remove it in the `MenuItemButton.on_click` callback.

**Comment by BrentHuang** [comment]
Thanks, I know I can do this, but it's a bit cumbersome

**Comment by ndonkoHenri** [comment]
Sorry for that, but you will have to do it that way for now.

**Comment by BrentHuang** [comment]
PopupMenuItem has 'checked' Property,  why not MenuItemButton?

**Comment by ndonkoHenri** [comment]
Sorry, but all controls are not similar.

**Comment by BrentHuang** [comment]
> Sorry, but all controls are not similar.

In practice, this is a very common menu feature.
