### ISSUE TITLE
Client storage issue I ran into, dict initialization

### ISSUE THREAD

**Issue by drawdel** [flet-dev/examples#137]
Running the following lines of code, my original code displayed the correct attributes on desktop mac, but None on web and ios. The debug messages 'item added' and 'item in list = True' was displayed on all 3 platforms, but on web and ios it displayed None instead of the expected attributes. The fix chatgpt gave me corrected it so that it now displays the correct attributes on all platforms. What was the issue here? I'm not an experienced programmer so I don't understand what happened. Is this something about Python I don't understand or something specific to flet?

functions_item.add_item(page, 'item_name', 23, 46, 15, 6, 2)
page.add(ft.Text(f"item_name has {functions_item.fetch_item_attributes(page, 'item_name')}"))

<img width="750" alt="Screenshot 2024-05-28 at 9 09 59 PM" src="https://github.com/flet-dev/examples/assets/123798612/b1938e7c-15ee-44b9-b32f-268b8ada53d2">
<img width="739" alt="Screenshot 2024-05-28 at 9 10 08 PM" src="https://github.com/flet-dev/examples/assets/123798612/adcb8fe0-23d9-478c-9e89-536dba293156">
Here's what ChatGPT says about the fix.
<img width="764" alt="Screenshot 2024-05-28 at 9 14 57 PM" src="https://github.com/flet-dev/examples/assets/123798612/2f91da90-fbd7-40bb-b919-1ad598c0633c">

**Comment by ndonkoHenri** [comment]
Please share some runnable code as text here, and not image/screenshot.

**Comment by ndonkoHenri** [comment]
> https://pastebin.com/huUV8w7E

The code is not runnable. Please provide some runnable code that i can easily run to test the issue and further help you.
