### ISSUE TITLE
How to make such an effect, web side

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/examples#145]
How to make such an effect, web side

![1720166961263](https://github.com/flet-dev/examples/assets/2862064/4ab8b5b7-3cae-4dc9-9f13-3e8240ed3fd4)

If the text does not fit in one line, it will automatically wrap.

**Comment by ndonkoHenri** [comment]
You can make use of `TextSpan`s: https://flet.dev/docs/controls/text#rich-text-basics

**Comment by BrentHuang** [comment]
thank you very much @ndonkoHenri
