### ISSUE TITLE
how to get the real theme currently?

### ISSUE THREAD

**Issue by BrentHuang** [flet-dev/examples#148]
in flet, I set page.theme_mode = 'system'.   But I need to get the real theme currently to switch the two img bellow in my code. How to do that?
![dark](https://github.com/user-attachments/assets/5250e1db-5eca-4dd3-bc32-6294e3002444)
![light](https://github.com/user-attachments/assets/814fdab6-a41f-4a6e-9046-25929e3162b8)

**Comment by ndonkoHenri** [comment]
Use [`page.platform_brightness`](https://flet.dev/docs/controls/page#platform_brightness)

**Comment by BrentHuang** [comment]
thank you
