### ISSUE TITLE
SVG Image error in Docker Container

### ISSUE THREAD

**Issue by nwolfe20** [flet-dev/examples#153]
I am trying to run my Flet app in a docker container using the dockerfile provided in the Solitaire Final Part 1. Still, every time it runs, it does not display all the cards and cannot display the back image either(Both from the Solitaire Github).
Here is the error it is showing in the browser Console: 
![image](https://github.com/user-attachments/assets/c3a9a8aa-e07b-46ec-bbb3-aca900ed6d95)
Image of the Docker FIle : 
![image](https://github.com/user-attachments/assets/2830bb9d-0304-4aeb-bdd6-818b68216735)
Image of the Directory:
![image](https://github.com/user-attachments/assets/2b04a4ed-67ec-4ff5-9e33-b4dc2ce8b191)

**Comment by nwolfe20** [comment]
I figured out a weird way of fixing this error. I made a JSON document with the key being the name of the image and the value being the base64 value of the image, and I used the srcbase64 image definition to create the image. For example it would read like this in my case 10_hearts; "string of base64 encoded svg file." This seemed to work for me if there is a better way please let me know!

**Comment by ndonkoHenri** [comment]
Can you share here an svg image you use?

**Comment by nwolfe20** [comment]
It is the SVG images from the Flet solitaire tutorial. I got all the card files from there
![image](https://github.com/user-attachments/assets/9eebf454-abd3-4047-87f1-b6e177a4863b)
