### ISSUE TITLE
Calculator example doesn't seem to respond to mouse clicks or key presses

### ISSUE THREAD

**Issue by jrobbins-LiveData** [flet-dev/examples#19]
I tried running [calc.py](https://github.com/flet-dev/examples/blob/main/python/tutorials/calc/calc.py) both desktop and browser and neither instance seems to respond to clicks or keys.  The other examples (`counter.py` and `todo.py`) work.  Not sure how to debug or diagnose further.

**Comment by FeodorFitsner** [comment]
What OS are you running it on?

**Comment by jrobbins-LiveData** [comment]
Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

**Comment by FeodorFitsner** [comment]
Do you get any errors in conse? How does that misbehavior look like?

**Comment by YeeKal** [comment]
I got the same error  at Ubuntu 18.04.6 LTS x86_64, there is not any errors or other warnings in console.
flet version is  0.1.54.

**Comment by FeodorFitsner** [comment]
OK, there was a bug related to a recent regression. I've updated Calc example and it works now: https://github.com/flet-dev/examples/edit/main/python/tutorials/calc/calc.py

**Comment by jrobbins-LiveData** [comment]
Thank you, @FeodorFitsner.  I can confirm that both the desktop app and the browser app `calc.py` work for me now, using mouse clicks.  Is it meant to also support the keyboard (not looking for scope creep, just wanting to confirm correct functioning!)
