### ISSUE TITLE
pubsub

### ISSUE THREAD

**Issue by orcim-wind** [flet-dev/examples#23]
HI,
I try the example pubsub after update Flet and dont' work

**Comment by FeodorFitsner** [comment]
Could you drop a link to the example please?

**Comment by orcim-wind** [comment]
https://github.com/flet-dev/flet/blob/main/sdk/python/flet/pubsub.py

**Comment by FeodorFitsner** [comment]
I mean could you share the app using pubsub that doesn't work?

**Comment by orcim-wind** [comment]
I used the script above in two terminal under linux and i have not seen any message to get to each other.
Ps. I cloned the last Flet, Example repositories

**Comment by FeodorFitsner** [comment]
https://github.com/flet-dev/flet/blob/main/sdk/python/flet/pubsub.py is not a ready-to-run program - it's an internal part of Flet package. Could you share your program using PubSub functionality?

**Comment by orcim-wind** [comment]
I have no program to share. I just wanted to try the functionality.

**Comment by FeodorFitsner** [comment]
Then use an example from this article: https://flet.dev/docs/guides/python/pub-sub

**Comment by orcim-wind** [comment]
I have the same result. i have not seen any message to get to each other
