### ISSUE TITLE
Creating a custom loading image and favicon

### ISSUE THREAD

**Issue by regstuff** [flet-dev/examples#55]
Could anyone guide me to a tutorial on how I can change the default loading image and icon. 

I checked this [tutorial](https://github.com/flet-dev/examples/blob/main/python/apps/custom-loading-image/assets/icons/loading-animation.png), but it doesn't seem to be working, or maybe I'm not using it right.

EDIT: Ok, playing around with a little more, changing the port did the trick. Seems like there is some kind of cache? I've disabled cache for the localhost in developer tools. Any idea how to get around this?

**Comment by FeodorFitsner** [comment]
I don't think there is anything in Flet explicitly caching static content. You can use a regular approach - changing file/icon name if you need updating an image on every release.
